/* eslint-disable */
// AUTO-GENERATED by app/src/scripts/mine-transitions.ts
// Do not edit by hand. Re-run the mining script after changing
// training-examples.md or PRIOR_BRIDGE.
//
// Smoothing formula: (empirical_sum + prior * 3) / (n + 3)
//
// Inline comments show: n=observations, emp=empirical mean, prior=hand-tuned prior

export const CATEGORY_BRIDGE: Record<string, Record<string, number>> = {
  analysis: {
    analytics: 55, // n=0, prior=55
    backend: 40, // n=0, prior=40
    design: 40, // n=0, prior=40
    management: 60, // n=0, prior=60
  },
  analytics: {
    analysis: 55, // n=0, prior=55
    backend: 75, // n=1, emp=75
    data: 63, // n=1, emp=25, prior=75
    management: 45, // n=0, prior=45
    marketing: 45, // n=0, prior=45
  },
  architecture: {
    analysis: 45, // n=0, prior=45
    backend: 65, // n=0, prior=65
    devops: 55, // n=0, prior=55
    management: 65, // n=0, prior=65
  },
  backend: {
    analysis: 40, // n=0, prior=40
    architecture: 65, // n=0, prior=65
    data: 55, // n=0, prior=55
    devops: 45, // n=0, prior=45
    frontend: 55, // n=0, prior=55
    fullstack: 70, // n=0, prior=70
    infra: 63, // n=3, emp=63
    management: 85, // n=1, emp=85
    mobile: 35, // n=0, prior=35
    qa: 40, // n=0, prior=40
  },
  data: {
    analytics: 76, // n=1, emp=78, prior=75
    backend: 55, // n=0, prior=55
    devops: 40, // n=0, prior=40
    management: 79, // n=2, emp=79
  },
  design: {
    frontend: 40, // n=0, prior=40
    management: 40, // n=0, prior=40
    marketing: 40, // n=0, prior=40
    mobile: 40, // n=0, prior=40
  },
  devops: {
    architecture: 55, // n=0, prior=55
    backend: 45, // n=0, prior=45
    data: 40, // n=0, prior=40
    infra: 70, // n=0, prior=70
    security: 55, // n=0, prior=55
    support: 50, // n=0, prior=50
  },
  docs: {
    analysis: 40, // n=0, prior=40
    hr: 30, // n=0, prior=30
  },
  frontend: {
    analytics: 55, // n=1, emp=55
    backend: 55, // n=0, prior=55
    design: 40, // n=0, prior=40
    fullstack: 70, // n=3, emp=70, prior=70
    infra: 45, // n=1, emp=45
    mobile: 54, // n=1, emp=80, prior=45
    qa: 40, // n=0, prior=40
  },
  fullstack: {
    backend: 74, // n=1, emp=85, prior=70
    frontend: 70, // n=0, prior=70
    infra: 55, // n=1, emp=55
    mobile: 50, // n=0, prior=50
  },
  gamedev: {
    backend: 30, // n=0, prior=30
    frontend: 35, // n=0, prior=35
    mobile: 45, // n=0, prior=45
  },
  hr: {
    docs: 30, // n=0, prior=30
    management: 40, // n=0, prior=40
    marketing: 35, // n=0, prior=35
  },
  infra: {
    devops: 70, // n=0, prior=70
    security: 50, // n=0, prior=50
    support: 55, // n=0, prior=55
  },
  management: {
    analysis: 60, // n=0, prior=60
    analytics: 45, // n=0, prior=45
    architecture: 65, // n=0, prior=65
    design: 40, // n=0, prior=40
    hr: 40, // n=0, prior=40
    marketing: 56, // n=1, emp=75, prior=50
  },
  marketing: {
    analytics: 45, // n=0, prior=45
    design: 40, // n=0, prior=40
    hr: 35, // n=0, prior=35
    management: 50, // n=0, prior=50
  },
  mobile: {
    backend: 35, // n=0, prior=35
    data: 33, // n=2, emp=33
    design: 40, // n=0, prior=40
    frontend: 45, // n=0, prior=45
    gamedev: 45, // n=0, prior=45
    infra: 50, // n=1, emp=50
  },
  qa: {
    backend: 40, // n=0, prior=40
    frontend: 40, // n=0, prior=40
    mobile: 35, // n=0, prior=35
  },
  security: {
    backend: 40, // n=0, prior=40
    devops: 55, // n=0, prior=55
    infra: 50, // n=0, prior=50
  },
  support: {
    devops: 50, // n=0, prior=50
    hr: 35, // n=0, prior=35
    infra: 55, // n=0, prior=55
  },
};
